In [2]:
import numpy as np

In [3]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:

np.add(a,1)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [7]:
np.divide(a,3)

array([6.66666667, 7.        , 7.33333333, 7.66666667, 8.        ,
       8.33333333, 8.66666667, 9.        , 9.33333333, 9.66666667])

In [9]:
a**2

array([400, 441, 484, 529, 576, 625, 676, 729, 784, 841])